complete/25--ThreeDoMVC/config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'

  resources :todos do
    collection do
      patch :toggle_all
      delete :clear_completed
    end
  end

end

complete/25--ThreeDoMVC/app/models/todo.rb
class Todo < ActiveRecord::Base

  def self.more_todo?
    where(complete: false).any?
  end

  def self.any_complete?
    where(complete: true).any?
  end

  def self.toggle_all
    toggle_to = more_todo?
    update_all(complete: toggle_to)
    toggle_to
  end

  def self.destroy_completed
    Todo.where(complete: true).destroy_all
  end
end

complete/25--ThreeDoMVC/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

complete/25--ThreeDoMVC/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index 
    @todo = Todo.new
    @todos = Todo.all
    set_up_bottom_row
  end

  def create
    @todo = Todo.create(todo_params(:name))
    @count = Todo.count
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params(:complete, :name))
    set_up_bottom_row
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    set_up_bottom_row
  end

  def toggle_all
    @toggle_to = Todo.toggle_all
    set_up_bottom_row
  end

  def clear_completed
    @todos = Todo.destroy_completed
  end

  private

    def todo_params(*attributes)
      params.require(:todo).permit(*attributes)
    end

    def set_up_bottom_row
      @count = Todo.where(complete: false).count
      @any_complete = Todo.any_complete?
      @more_todo = Todo.more_todo?
    end
end

complete/25--ThreeDoMVC/app/helpers/application_helper.rb
module ApplicationHelper
end

complete/25--ThreeDoMVC/app/helpers/todos_helper.rb
module TodosHelper
end

complete/25--ThreeDoMVC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoMvcV3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

complete/25--ThreeDoMVC/app/views/todos/_bottom_row.js.erb
$("#todo-count").replaceWith("<%= j(render partial: 'count', 
                              locals: { count: count }) %>");
// update the clear-completed link
// hide if there are no incomplete items
// show if there are any complete items
<% if complete %>
  $("#clear-completed").show();
<% else %>
  $("#clear-completed").hide();
<% end %>

complete/25--ThreeDoMVC/app/views/todos/_count.html.erb
<span id="todo-count">
  <strong><%= count %></strong> item<%= 's' if count != 1 %> left
</span>

complete/25--ThreeDoMVC/app/views/todos/_new_todo.html.erb
<%= form_for todo, remote: true do |f| %>
  <%= f.text_field :name, id: 'new-todo', 
                          placeholder: "What needs to be done?", autofocus: true %>
<% end %>

<!-- the above partial generates this html
<form class="new_todo" id="new_todo" action="/todos" accept-charset="UTF-8" data-remote="true" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input id="new-todo" placeholder="What needs to be done?" autofocus="autofocus" type="text" name="todo[name]">
</form>
-->

<!-- the most important parts of the html are these
<form action="/todos" method="POST" data-remote="true">
      <input id="new-todo" placeholder="What needs to be done?"  name=
      "todo[title]" autofocus>
    </form>
-->

complete/25--ThreeDoMVC/app/views/todos/_todo.html.erb
<li <%= 'class=completed' if todo.complete? %> id="todo_<%= todo.id %>">
  <!-- If this list item is being edited, the div.view can be omitted -->
  <div class="view">
    <%= form_for todo, remote: true do |f| %>
      <%= f.check_box :complete, class: 'toggle' %>
    <% end %>
  <!-- <form class="edit_todo" id="edit_todo_1" action="/todos/1" accept-charset="UTF-8" data-remote="true" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="_method" value="patch">
    <input name="todo[complete]" type="hidden" value="0">
    <input class="toggle" type="checkbox" value="1" name="todo[complete]" id="todo_complete">
</form> -->
    <a><%= todo.name %></a>
    <%= button_to todo, method: :delete, remote: true, class: 'destroy' do %>
    <% end %>
  </div>
  <!-- The following form should appear only if this list item is being edited -->
  <%= form_for todo, remote: true do |f| %>
    <%= f.text_field :name, class: 'edit' %>
  <% end %>
</li>

complete/25--ThreeDoMVC/app/views/todos/_toggle_all.html.erb
<%= form_tag toggle_all_todos_path, remote: true, method: :patch do %>
  <%= check_box_tag :toggle_all, 1, any_complete, id: 'toggle-all' %>
  <%= label_tag :toggle_all, "Mark all as complete", for: 'toggle-all' %>
<% end %>

complete/25--ThreeDoMVC/app/views/todos/clear_completed.js.erb
<% @todos.each do |todo| %>
  $("#todo_<%= todo.id %>").remove();
<% end %>

complete/25--ThreeDoMVC/app/views/todos/create.js.erb
$("#new_todo input[name*='name']").val('');
$("<%= j(render @todo) %>").appendTo('#todo-list');
/* render partial: 'todo', locals: { todo: @todo }
same as
render @todo, because @todo is a single Todo item

render partial: 'todo', collection: @todos
same as
render @todos, because @todos is a collection of Todo items 
*/


$("#todo-count").replaceWith("<%= j(render partial: 'count', locals: { count: @count }) %>");
/* render partial: 'count' looks like
// <span id="todo-count"><strong>5</strong> items left</span>
// call escape_javascript (or its synonym, j) on the partial to get
// <span id=\"todo-count\"><strong>5<\/strong> items left<\/span> 
*/
<% if @count == 1 %>
  $("#todo-list").before("<%= j(render(partial: 'toggle_all', locals: { any_complete: false })) %>")
<% end %>

complete/25--ThreeDoMVC/app/views/todos/destroy.js.erb
$("#todo_<%= @todo.id %>").remove();
// update the todo count
<%= render partial: 'bottom_row', locals: { count: @count,
                                            complete: @any_complete } %>

complete/25--ThreeDoMVC/app/views/todos/index.html.erb
<section id="todoapp">
  <header id="header">
    <h1>todos</h1>
    <%= render partial: 'new_todo', locals: { todo: @todo } %>
  </header>
  <!-- This section should be hidden by default and shown when there are todos to display -->
  <section id="main">
    <%= render partial: 'toggle_all', locals: { any_complete: @any_complete } if @todos.count > 0 %>
    <ul id="todo-list">
      <!-- These are here just to show the structure of the list items -->
      <!-- List items should get the class `editing` when editing and `completed` when marked as completed -->
      <%= render @todos %>
    </ul>
  </section>
  <!-- This footer should hidden by default and shown when there are todos -->
  <footer id="footer">
    <!-- This should be `0 items left` by default -->
    <%= render partial: 'count', locals: { count: @todos.count } %>
    <ul id="filters">
      <li>
        <a class="selected" href="/">All</a>
      </li>
      <li>
        <a href="/active">Active</a>
      </li>
      <li>
        <a href="/completed">Completed</a>
      </li>
    </ul>
    <!-- Hidden if no completed items are left ↓ -->
    <%= button_to clear_completed_todos_path, remote: true, id: 'clear-completed', class: "#{'hidden' unless @any_complete}", method: :delete do %>
      Clear completed
    <% end %>
  </footer>
</section>
<footer id="info">
  <p>Double-click to edit a todo</p>
  <!-- Change this out with your name and url ↓ -->
  <p>Created by <a href="http://todomvc.com">you</a></p>
  <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>

complete/25--ThreeDoMVC/app/views/todos/toggle_all.js.erb
$("#todo-list li").<%= @toggle_to ? 'add' : 'remove' %>Class('completed').find('input[type="checkbox"]').prop('checked', <%= @toggle_to %>);

<%= render partial: 'bottom_row', locals: { count: @count,
                                            complete: @any_complete } %>

complete/25--ThreeDoMVC/app/views/todos/update.js.erb
// when a todo is toggled,
// add or remove the completed class to the li
$("#todo_<%= @todo.id %>").<%= @todo.complete?? 'add' : 'remove' %>Class("completed");
console.log($("#todo_<%= @todo.id %>"));
// check or uncheck the toggle all checkbox
$('#toggle-all').prop('checked', <%= !@more_todo %>);

<%= render partial: 'bottom_row', locals: { count: @count,
                                            complete: @any_complete } %>

$("#todo_<%= @todo.id %>").removeClass('editing');
$("#todo_<%= @todo.id %> a").text("<%= @todo.name %>");

if($("#filters .selected").attr('href') == "/active" && <%= @todo.complete? %>){
  $("#todo_<%= @todo.id %>").hide();
}